Further work on the disassembly feature.
KDAB/hotspot pull request #273
Opened 2020-12-18 06:32 UTC by dknysh

Hello, Milian.
You requested some Further work on disassembly feature.

a) Hoist DisassemblyOutput::disassemble code chunk out into a separate
file and then build a simple test which runs this on some of the known symbols
in one of our existing test binaries, such as

../3rdparty/perfparser/tests/auto/perfdata/vector_static_gcc/
vector_static_gcc_v9.1.0

Could you please review the implementation for the point.

P.S. Could you please also clarify what do you mean as proper model in the second point - 

       b) We need a proper item model implementation on top of the DisassemblyOutput.
           Together with a model test then too.

Thank you,
Darya.

2020-12-18 11:19 UTC, milianw requested changes
thank you!

regarding the model: I mean implementing a real model instead of using QStandardItemModel which is notoriously bad and should only be used for prototyping purposes. Basically it would be a custom class that inherits from QAbstractTableModel and operaters directly on the `QVector<DisassemblyOutput::DisassemblyLine>` and corresponding costs internally then

2020-12-18 11:19 UTC, milianw commented on src/models/disassemblyoutput.h
> +#include "data.h"
don't include the header here, forward declare the Symbol struct instead

2020-12-18 11:19 UTC, milianw commented on tests/modeltests/tst_disassemblyoutput.cpp
> +        Data::Symbol curSymbol = {QLatin1String("__cos_fma"),
pass the symbol in as another QTest column, then only patch/overwrite the actualBinaryFile here

2020-12-18 11:19 UTC, milianw commented on tests/modeltests/tst_disassemblyoutput.cpp
> +        Data::Symbol curSymbol = {QLatin1String("__cos_fma"),
also: here and below these should be QStringLiteral instead of QLatin1String, or remove it altogether - in a test that's OK imo

2020-12-18 11:19 UTC, milianw commented on src/resultsdisassemblypage.h
> +#include "models/disassemblyoutput.h"
forward declare instead and only include in .cpp file

2020-12-21 13:52 UTC, milianw requested changes
cool, three more little cleanups then this can go in

2020-12-21 13:52 UTC, milianw commented on tests/modeltests/tst_disassemblyoutput.cpp
> +        QVector<DisassemblyOutput::DisassemblyLine> disassemblyLines = disassemblyOutput.disassemblyLines;
unused, remove

2020-12-21 13:52 UTC, milianw commented on tests/modeltests/tst_disassemblyoutput.cpp
> +            QFile actual(actualOutputFile);
open the file earlier above, then write directly to it via a QTextStream in the loop above instead of first building a list and then joining it

2020-12-21 13:52 UTC, milianw commented on tests/modeltests/tst_disassemblyoutput.cpp
> +        for (int row = 0; row < disassemblyOutput.disassemblyLines.size(); row++) {
for (const auto &disassemblyLine : disassemblyOutput.disassemblyLines);

2020-12-22 05:14 UTC, dknysh commented
Updated accordingly your remarks.

2020-12-22 15:57 UTC, merged

2020-12-22 15:57 UTC, milianw commented
thank you