add option for user to set stack dump size
KDAB/hotspot pull request #296
Opened 2021-06-16 14:38 UTC by lievenhey

when profiling huge applications the default stack dump of 8192 bytes
might be a little small

I added a combobox where the user can choose between 1024 and 16384

I am thinking about changing the combobox to a editable one to allow the user to change the value to their liking. Is this a good Idea?

2021-06-17 13:11 UTC, milianw requested changes
this is implemented already via the mmapPagesArg?

2021-06-17 13:26 UTC, lievenhey commented
no, mmapPagesArg is for --mmap-pages while mine is used for --call-graph when dwarf unwinding is selected

2021-06-17 19:26 UTC, milianw requested changes
I stand corrected

2021-06-17 19:26 UTC, milianw commented on src/recordpage.cpp
> +        // these elements only need to hide if the user changed the callgraph method
this comment is misplaced, it should be moved into the connect below

2021-06-17 19:26 UTC, milianw commented on src/recordpage.cpp
> +                if (ui->callGraphComboBox->itemData(index) == QStringLiteral("dwarf")) {
simplify and use QLatin1String:
```
const auto isDwarf = ui->...->itemData(index).toString() == QLatin1String("dwarf");
ui->stackDumpComboBox->setVisible(isDwarf);
...
```

2021-06-17 19:26 UTC, milianw commented on src/recordpage.cpp
> +    connect(ui->callGraphComboBox, static_cast<void (QComboBox::*)(int)>(&QComboBox::currentIndexChanged), this,
use `qOverload`

2021-06-17 19:26 UTC, milianw commented on src/recordpage.cpp
> +            if (callGraphOption == QStringLiteral("dwarf")) {
hoist out the common code:

```
perfOptions << QStringLiteral("--call-graph");
if (callGraphOption == QLatin1String("dwarf"))
    ...
else
  ...
```

2021-06-30 12:47 UTC, milianw approved these changes

2021-06-30 12:47 UTC, merged