add setting to choose the eliding mode for the flamegraph
KDAB/hotspot pull request #395
Opened 2022-07-20 11:56 UTC by lievenhey

in some cases the flamegraph contains only std::... and not the function
name.
This patch allows the user to change the eliding to ElideLeft so that
you can see the function name

2022-08-28 10:32 UTC, milianw requested changes
instead of making this configurable, I'd say we should make the elision more useful?

 Neither left nor right elision is ideal for absurd symbols like

```
asdf_namespace::foobar<asdf, yxcvyxcv>::blablub(someotherreallylongnames, ...)
```

ideally, we would detect such long names and then iteratively elide them, such that:

a) first we drop the function arguments and the above gets turned into
```
asdf_namespace::foobar<asdf, yxcvyxcv>::blablub(...)
```
b) if that's still too long, we left remove template arguments (we have that already, reuse that logic)
```
asdf_namespace::foobar<...>::blablub(...)
```
c) finally if that's still too long, we left-elide the remainder to produce e.g. (depending on width):
```
...::blablub(...)
```

ideally we also don't use three dots but the utf8 sequence for the ellision, i.e. `…`

2022-08-28 10:32 UTC, milianw commented on src/settings.cpp
> +    Q_ASSERT(mode == Qt::ElideLeft || Qt::ElideRight);
this check is always true because Qt::ElideRight is always true

2022-09-30 19:06 UTC, milianw commented on tests/modeltests/tst_models.cpp
> +            QLatin1String("asdf_namespace::foobar<asdf, yxcvyxcv>::blablub(someotherreallylongnames) const");
QStringLiteral

2022-09-30 19:07 UTC, milianw commented on src/util.cpp
> +QString elideArguments(const QString symbolText)
const&

2022-10-07 12:08 UTC, milianw commented on src/util.cpp
> +    int startEliding = symbolText.indexOf(QLatin1Char('('));
https://invent.kde.org/kdevelop/kdevelop/-/merge_requests/378 contains a bunch of other fancy identifiers that are hard to parse...

2022-11-07 12:38 UTC, lievenhey commented on src/util.cpp
> +    int startEliding = symbolText.indexOf(QLatin1Char('('));
I added some more logic, so that hotspot is now able to elide those monstrosities

2022-11-11 22:27 UTC, milianw requested changes

2022-11-11 22:27 UTC, milianw commented on src/util.cpp
> +    QString first;
`std::pair<QString, QString>`? or use better names

2022-11-11 22:27 UTC, milianw commented on src/util.cpp
> +    const auto elideSymbol = QString::fromUtf8("…");
this is not resolved

2022-11-11 22:27 UTC, milianw commented on src/util.cpp
> +    const auto elideString = QString::fromUtf8("<…");
not resolved

2022-11-11 22:27 UTC, milianw commented on tests/modeltests/tst_models.cpp
> +            QLatin1String("asdf_namespace::foobar<asdf, yxcvyxcv>::blablub(someotherreallylongnames) const");
not done

2022-11-11 22:27 UTC, milianw commented on tests/modeltests/tst_models.cpp
> +        const QString symbol = QLatin1String("Foo<&bar::operator()>::asdf<XYZ>(blabla<&foo::operator(), ')', '('>)");
dito

2022-11-11 22:27 UTC, milianw commented on src/util.cpp
> +    for (int i = symbolText.length() - 1; i > 0; i--) {
please add some basic comments that document what this code is doing on a high level

2022-11-15 08:15 UTC, milianw approved these changes
lgtm, thanks

2022-11-15 08:15 UTC, merged