add an improved color scheme for the flamegraph
KDAB/hotspot pull request #399
Opened 2022-09-15 09:17 UTC by lievenhey

the new color scheme selects the color based on the cost in % an very expensive function is colored red, a cheap function is colored yellow

2022-09-15 09:18 UTC, lievenhey commented
![grafik](https://user-images.githubusercontent.com/82457690/190366173-dfa63178-d54a-4fab-bea4-6d5942420009.png)

2022-09-30 18:50 UTC, milianw requested changes
I'm fine with adding it, but not under this name. it doesn't improve anything, it's just a different way to colorize it - and note how it essentially duplicates information that we already represent in the flamegraph: the width already encodes the cost ratio, so doing it again with the color... what for?

2022-09-30 18:50 UTC, milianw commented on src/flamegraph.cpp
> +QBrush improvedBrush(quint32 cost, quint32 totalCost)
"improved" is very subjective. I don't think it improves anything. please give it a different name, something like `brushByCostRatio` or similar

2022-09-30 18:50 UTC, milianw commented on src/flamegraph.cpp
> +    m_colorSchemeSelector->addItem(tr("Improved"), QVariant::fromValue(Settings::ColorScheme::Improved));
Cost Ratio

2022-09-30 18:50 UTC, milianw commented on src/settings.h
> +        Improved,
CostRatio

2022-10-07 17:35 UTC, milianw commented
please rebase, the compile errors should be gone

2022-10-11 09:29 UTC, lievenhey commented
done

2022-10-20 08:41 UTC, milianw approved these changes

2022-10-20 08:41 UTC, merged