Perf map select
KDAB/hotspot pull request #510
Opened 2023-09-21 15:50 UTC by lievenhey

fixes: #498
requires: https://github.com/KDAB/perfparser/pull/27

2023-09-21 16:04 UTC, lievenhey commented
tested with `perf record --call-graph=dwarf  java -XX:+PreserveFramePointer -XX:+UnlockDiagnosticVMOptions -XX:+DumpPerfMapAtExit CryptoBench.java` and CryptoBench.java from https://bell-sw.com/announcements/2022/04/07/how-to-use-perf-to-monitor-java-performance/

2023-09-22 08:29 UTC, milianw requested changes

2023-09-22 08:29 UTC, milianw commented on src/parsers/perf/perfparser.cpp
> +            parserArgs += {QStringLiteral("--perf-map-path"), QStringLiteral("/home/lieven/KDAB/hotspot")};
bad hardcoded path

2023-09-28 07:38 UTC, milianw approved these changes

2023-09-28 07:39 UTC, merged