fix out of range access
KDAB/hotspot pull request #530
Opened 2023-10-17 12:39 UTC by lievenhey

start was set to current + 1 which will cause undefined behavior if current is the last element
this patch adds a check for this and wraps around in that case

fixes: #526

2023-10-17 12:40 UTC, lievenhey commented
I have to check the output of the appimage build since the warning is only shown there

2023-10-17 14:58 UTC, milianw requested changes
add a test for this case please

2023-10-19 09:04 UTC, lievenhey commented
How do I test this? Since gcc 5 `std::find_if` returns `end` if `begin` > `end` (figured out by playing with godbolt, since this error only happens on old compilers)

2023-10-19 09:57 UTC, milianw requested changes

2023-10-19 09:57 UTC, milianw commented on src/models/search.h
> +    iter start;
```
auto start = (current == end) ? begin : (current + 1);
```

2023-10-19 12:16 UTC, merged