Disable disassembly of inline functions
KDAB/hotspot pull request #568
Opened 2023-12-05 14:38 UTC by lievenhey

Currently this doesn't work correctly. In the flamegraph the top entry doesn't has the inline flag set.
![grafik](https://github.com/KDAB/hotspot/assets/82457690/72f7559b-f1c1-4990-acc6-f289c66b8949)

2023-12-05 18:17 UTC, milianw requested changes
can we get a test too please? :)

2023-12-05 18:17 UTC, milianw commented on src/models/callercalleemodel.cpp
> +        case IsInline:
I don't think it's worthwhile to add this detail to the caller/callee model as a column. just showing it in a tooltip should be fine?

or can you at least make sure that this column is hidden by default?

2023-12-05 18:17 UTC, milianw commented on src/models/callercalleemodel.cpp
> +            return {};
either remove this column or add something here

2023-12-05 18:17 UTC, milianw commented on src/models/callercalleemodel.cpp
> +            return 0;
this should also return symbol.isInline

2023-12-05 18:17 UTC, milianw commented on src/models/data.h
>      {
you need to handle isInline here too - and isKernel as well, apparently that's borken?

2023-12-05 18:17 UTC, milianw commented on src/models/data.h
> +    bool isKernel;
keep the = false, add it for isInline too

2023-12-07 08:35 UTC, lievenhey commented
The second commit is just for debugging. I will remove it once everything works.

2023-12-07 11:40 UTC, lievenhey commented
I also added a color scheme to the flamegraph to show which functions are inlined.
![grafik](https://github.com/KDAB/hotspot/assets/82457690/b599ebeb-e1e1-4037-a887-739be6bde407)

2023-12-09 20:17 UTC, milianw commented
Cool, can you also add the combined mode, that shows system code / user code / inlined code? I think that is going to be very useful

2023-12-09 21:47 UTC, milianw commented
OK, you can rebase, I fixed the issue with the duplicate inline frame now

2023-12-11 13:55 UTC, lievenhey commented
I also had to remove the costBrush since:
- it wasn't really useful
- it broke and created colors that ware outside the hsv scope

2023-12-11 14:07 UTC, lievenhey commented
the ci not working is expected, since I updated it to kddw 2.0 this morning. It will work once #570 is landed

2023-12-19 09:57 UTC, GitMensch commented
This seems to still needing an automated test of some sort, right?
Apart from that this seems ready to merge and looks very useful.

2024-01-02 14:14 UTC, milianw commented
Hey @lievenhey - I revamped the colorization of inline frames in the flamegraph, and include the info now also in tooltips. Can you give it another shot and see if that works for you too?

From my side, this is otherwise fine now.

2024-01-02 14:17 UTC, GitMensch commented
This sounds good to me, but it looks like adjustment to README / doc pngs are "missing".
Of course I'm fine with both handling those here as well as a follow-up PR.

2024-01-02 14:17 UTC, GitMensch commented
> From my side, this is otherwise fine now.

Note @milianw: at least from the PR state it still has "change requested" from you.

2024-01-02 15:25 UTC, GitMensch commented
I've tinkered with the appimage, and found the flame-graph to be quite reasonable now (much better than the previous one).
... but: I'm not sure about the inline function costs and the disassembly.

![grafik](https://github.com/KDAB/hotspot/assets/6699539/b6a26cd5-99b9-4c7e-8a0b-d3fc5a5e041e)
![grafik](https://github.com/KDAB/hotspot/assets/6699539/5c3346e7-e0ed-459b-9293-499dae2d780a)

Of course, there is no option any more to use the "Disassembly" context on the inlined functions, which is fine, but I can't see neither the costs in the Disassembly of the caller nor the Disassembly for it either:

![grafik](https://github.com/KDAB/hotspot/assets/6699539/fa09cbff-34eb-4364-8fc6-7fe69165020d)

Where should one see those 25%?

2024-01-02 15:39 UTC, milianw commented
@GitMensch please open a new issue for whatever you are seeing there, and reproduce the issue in a way we can replicate it ourselves. As is there's not enough information for me to give you an answer to your question.

2024-01-02 15:39 UTC, milianw approved these changes

2024-01-02 15:40 UTC, GitMensch commented
Hm, that likely takes a while... short summary: the disassembly of inline functions has NO cost at all with this version, while it should have the cycles incl. set to the one that _is_ visible in the Caller/Callee tab.

2024-01-02 19:06 UTC, milianw commented
How do you get disassembly of an inline function to begin with? that shouldn't be possible anymore after all?!

2024-01-02 23:03 UTC, GitMensch commented
> How do you get disassembly of an inline function to begin with? that shouldn't be possible anymore after all?!

as noted: the disassembly of one function included the disassembly for a good part of the source, including (one of the generations of) the inline function. Showing the disassembly or not here isn't the main point I have with the effect of this PR, it is that the inlined function has no cost shown in the source code window anymore (you only see that by the caller/callee tab)...

2024-01-03 20:01 UTC, milianw commented
the inline symbol shouldn't even show up in the disassembly view at all, thus it not showing any cost there is to be expected, no? after all, we cannot open the disassembly for that anymore... I really don't follow what the issue is here, there seems to be a fundamental misunderstanding between us on how things should be working...

2024-01-08 10:40 UTC, lievenhey commented
> Hey @lievenhey - I revamped the colorization of inline frames in the flamegraph, and include the info now also in tooltips. Can you give it another shot and see if that works for you too?
> 
> From my side, this is otherwise fine now.

thanks, I suck at choosing color schemes.

2024-01-08 11:01 UTC, GitMensch commented
> the inline symbol shouldn't even show up in the disassembly view at all, thus it not showing any cost there is to be expected, no? after all, we cannot open the disassembly for that anymore... I really don't follow what the issue is here, there seems to be a fundamental misunderstanding between us on how things should be working...

I try to explain what I've thought to understand and what I think should be the UI for that.

* "real" inline (the compiler is free to inline or not after all) means that the compiler includes the code for a function within another function
* the actual generation (and therefore the diassembly) _may_ be different in each place concerning the context (for example a compiler may recognize that specific parts can only be taken in specific cases and remove the other parts)
* `perf` should trace the execution of that as it is tracing non-inlined code

Running `objdump` shows the disassembly for the "outer" function, therefore the inlined code is part of the disassembly, possibly multiple times (=  we can "see" the specific generation for this specific place).
Code-wise we see a function call.

If we can deduce the place of that disassembly to be part of the "calling" place (where it is inlined) then we can directly attribute the costs there.

If we can't do it, then we still have the "original" place (source reference and/or function name) and on the other hand we have the costs in the function of "calling" it (this is something that can be seen in the caller/callee tab, also with this PR applied).
Ideally we'd then be able to attribute the "summed" costs for the disassembly to the calling place -but I do recognize that in this case we'd have to match that in the code, which is not possible to always get correct because of the preprocessor work (for example macros) - we shouldn't start that path.

This leaves the question: Is there a way to deduce the "calling" source reference for functions that are inlined? If we yes, then we should attribute the total costs to that place.

2024-01-08 13:45 UTC, lievenhey commented
I created an issue for this #586

2024-01-12 14:18 UTC, milianw approved these changes

2024-01-13 12:34 UTC, merged