[enhancement] cut 60% time for PerfParser::filterResults
KDAB/hotspot pull request #571
Opened 2023-12-10 21:54 UTC by MuchToMyDelight

When change to "aggregate cost by symbol", filterResults spends a lot of time doing string comparison. This patch will reduce it dramatically.

Test on a 240MB perf.data/6 core CPU. The time of switching to "aggregate cost by symbol" is reduced from 50.x seconds to 19.x seconds.

2023-12-11 13:12 UTC, milianw requested changes
I'm fine with this in principle, but you'll have to make all the members private and add getter/setter  API, as otherwise it's too easy to break the code by accidentally mutating a symbol member without updating the hash.

furthermore, while at it, the `qHash` code should be inlined and `qHash(Symbol)` should just forward the cached hash then directly

2023-12-11 14:28 UTC, GitMensch commented
Thank you for inspecting this. The approach seems quite reasonable.

Note: #534 is related - is the `qHash()` commonly called by that `std:tie()`?
In general: could you provide a perfparser file (File->save) of a recording before and after the change?

2023-12-11 16:51 UTC, MuchToMyDelight commented
> I'm fine with this in principle, but you'll have to make all the members private and add getter/setter API, as otherwise it's too easy to break the code by accidentally mutating a symbol member without updating the hash.
> 
> furthermore, while at it, the `qHash` code should be inlined and `qHash(Symbol)` should just forward the cached hash then directly

Hello milianw! I totally agree with you about that all members should be private, actually that was what I did for my first version. The only thing is that it involves tons of change to the code as struct Symbol is used widely. So I think it's better to show the idea firstly. I'll update the PR later.

2023-12-12 04:58 UTC, MuchToMyDelight commented
Updated the PR and here is how it's tested:
Firstly, use perf to record a systemwide 60s. Then open it with hotspot, profling the time cost of switching from aggreate cost by process to symbol, under the tab "Bottom up"

The base version: origin/master, notice that operator== takes 50.6% time. total time **24.x** seconds
![base](https://github.com/KDAB/hotspot/assets/5919474/54d618e8-85e5-4999-b666-9d58cccf1b24)


The optimized version: the cost of operator== has gone, the time is reduced to **10.x** seconds
![optimized](https://github.com/KDAB/hotspot/assets/5919474/10658038-9cf8-4f22-bc23-a894ee7d5c9f)

2023-12-12 10:12 UTC, lievenhey commented
Don't worry about the neonqt6 error, that one is already fixed in master, just rebase.

2023-12-12 16:09 UTC, MuchToMyDelight commented
passed clany-tidy and pre-commit. 
However, I found that this test failed in origin/master both with or without this PR
``` text
QWARN  : TestPerfParser::testCppInliningEventCyclesInstructions(leader-sampling) hotspot.perfparser: Unexpected attribute id: -1 Only know about 2 attributes so far
QWARN  : TestPerfParser::testCppInliningEventCyclesInstructions(leader-sampling) hotspot.perfparser: Unexpected attribute id: -1 Only know about 2 attributes so far
QFATAL : TestPerfParser::testCppInliningEventCyclesInstructions(leader-sampling) ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qvector.h, line 457
FAIL!  : TestPerfParser::testCppInliningEventCyclesInstructions(leader-sampling) Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 10 passed, 15 failed, 0 skipped, 0 blacklisted, 5196ms
********* Finished testing of TestPerfParser *********


89% tests passed, 1 tests failed out of 9

Total Test time (real) =  12.99 sec

The following tests FAILED:
          9 - tst_perfparser (Subprocess aborted)
Errors while running CTest

````

2023-12-13 00:31 UTC, MuchToMyDelight commented
In comparison, I submitted another pull #574 . I'm undecided which one is better. What's your opinion? @milianw @GitMensch

2023-12-14 19:23 UTC, milianw commented
Are you ok if we abandon/close this one in favor of the other pull request which is imo much nicer?

2023-12-16 04:17 UTC, MuchToMyDelight commented
closing this one, prefer #574

2023-12-16 04:17 UTC, closed without merging