update kdesrc-build
KDAB/hotspot pull request #619
Opened 2024-04-24 14:28 UTC by lievenhey

There were some changes so the old version doesn't build anymore. This version also reduces the amount of build modules by disabling optional modules that were build with --include-dependencies

2024-04-24 14:32 UTC, milianw requested changes
this is not clean and I would prefer to only get it working first and then trim down deps next - not in one big blob

2024-04-24 14:32 UTC, milianw commented on scripts/appimage/Dockerfile
> +		fuse fuse-libs bzip2 \
odd indentation

2024-04-24 14:32 UTC, milianw commented on scripts/appimage/Dockerfile
> +    && qmake . && make -j && mv libqcustomplot.so* /usr/lib && cd /opt && rm -Rf qcustomplot && ldconfig
keep the nproc?

2024-04-24 14:32 UTC, milianw commented on scripts/appimage/Dockerfile
> +    # sed -i -e "s/%VERSION%/${KF5_VERSION}/g" kf5-frameworks-build-include  && \
remove / cleanup

2024-04-24 14:32 UTC, milianw commented on scripts/appimage/Dockerfile
> +# # kddockwidgets
?

2024-04-24 14:32 UTC, milianw commented on scripts/appimage/Dockerfile
> +# CMD ["find /github/workspace/"]
cleanup

2024-04-25 09:00 UTC, lievenhey commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DWITH_WAYLAND=OFF
I removed it since we don't ship the qt wayland qpa

2024-04-25 09:01 UTC, lievenhey commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DFORCE_DISABLE_KGLOBALACCEL=ON
we don't ship the qt wayland qpa so we don't need this

2024-04-25 09:01 UTC, lievenhey commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DWITH_KAUTH=OFF -DBUILD_DESIGNERPLUGIN=OFF
we don't use kauth

2024-04-25 09:01 UTC, lievenhey commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DBUILD_RUNTIME=OFF
we don't ship qt wayland so we don't need kglobalaccel

2024-04-25 09:03 UTC, lievenhey commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DFORCE_DISABLE_KGLOBALACCEL=ON
And I don't think we need those (unless you want to execute a shortcut without focusing hotspot)

2024-04-25 09:06 UTC, lievenhey commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DKIOCORE_ONLY=ON
It removed the gui stuff. I looked it up an KUrlRequester is a kio component so I am going to revert this.

2024-04-25 10:02 UTC, closed without merging

2024-04-25 10:38 UTC, milianw commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DBUILD_RUNTIME=OFF
I thought we do want to ship it in the future though, no? or do you think its not worth it and sticking to x11/xwayland is sufficient for the purpose of the appimage?

2024-04-25 10:39 UTC, milianw commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DWITH_KAUTH=OFF -DBUILD_DESIGNERPLUGIN=OFF
are you sure that it's also not used by e.g. KIO or the like internally? opening a file from another user or some other server?

2024-04-25 10:39 UTC, milianw commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DWITH_WAYLAND=OFF
I thought we do want to ship it in the future though, no? or do you think its not worth it and sticking to x11/xwayland is sufficient for the purpose of the appimage?

2024-04-25 10:39 UTC, milianw commented on scripts/appimage/kdesrc-buildrc
> +	cmake-options -DFORCE_DISABLE_KGLOBALACCEL=ON
ok add a comment then please to explain this