Update readme
KDAB/hotspot pull request #650
Opened 2024-05-28 14:34 UTC by lievenhey

2024-05-29 21:01 UTC, GitMensch commented
Possibly missing: hint at the 'new' "go to" command via context menu if there is not a totally clean way to reach it that I've missed.

Do I misremember that the arrows were drawn as lines instead of ascii?

2024-05-31 10:02 UTC, milianw commented on README.md
> +An inlined functions has a darker border compared to a normal function.
ack, functions -> function, or better yet rephrase to:

Note: Inlined functions have a darker border than non-inlined ones.

2024-05-31 18:01 UTC, GitMensch commented
Possibly add to the command line options as well after merging #653.

2024-06-04 11:04 UTC, lievenhey commented
> Do I misremember that the arrows were drawn as lines instead of ascii?

That is a feature that @milianw added some time ago

2024-06-04 12:26 UTC, GitMensch requested changes
English messages - then fine to merge.

Thank you for updating the screenshots to have the nice lines in as well.

Concerning the flamegraph - maybe some of the perf.data testfiles in the repo look "more interesting" while still showing the darker (inlined) frames?

2024-06-04 12:40 UTC, lievenhey commented
:facepalm:

2024-06-06 10:15 UTC, milianw approved these changes

2024-06-06 10:42 UTC, merged