Improve compressed files
KDAB/hotspot pull request #678
Opened 2024-09-17 16:53 UTC by lievenhey

2024-09-17 17:00 UTC, lievenhey commented
This is a fix for the currently broken compressed files feature. The current implementation doesn't work, because I passed the compressed file to `perfparser`. This patch series fixes that and adds support for archives files so that hotspot can now open `zip` and `tar.gz` files.

2024-09-18 20:09 UTC, GitMensch commented
Does this overlap with #633?

2024-09-26 12:20 UTC, milianw requested changes

2024-09-26 12:20 UTC, milianw commented on src/parsers/perf/perfparser.cpp
> +    auto parsingStopped = [this] { m_isParsing = false; };
can we get a test for this patch please?

2024-09-26 12:20 UTC, milianw commented on src/parsers/perf/perfparser.cpp
> +    for (const auto& file : {QStringLiteral("perf.data"), QStringLiteral("perf.data.perfparser")}) {
reuse utility function you are adding in the other patch

2024-09-26 12:20 UTC, milianw commented on tests/integrationtests/tst_perfparser.cpp
> +    void testArchive_data()
squash this into the previous patch

2024-09-26 12:23 UTC, milianw commented on tests/integrationtests/tst_perfparser.cpp
> +        QTest::addRow("uncompressed tar") << qUncompress(QByteArray::fromBase64(QByteArrayLiteral(
this is really ugly and opaque stuff that I feel uncomfortable with it, can we find another way?

2024-09-26 12:23 UTC, milianw commented on tests/integrationtests/tst_perfparser.cpp
> +        qDebug() << qCompress(content).toBase64();
remove?

2024-11-18 19:03 UTC, milianw approved these changes

2024-11-18 19:04 UTC, milianw commented on src/parsers/perf/perfparser.cpp
> +    for (const auto& file : {QStringLiteral("perf.data"), QStringLiteral("perf.data.perfparser")}) {
fine then, let's get this in as-is then!

2024-11-19 09:57 UTC, lievenhey commented
Ok I found a way to make it work with one function.
That patch also refactors a lot of code. Mainly the use of `#include <../utils.h>` in the model classes. This is done by moving that code to the models.

2024-11-19 12:30 UTC, milianw approved these changes

2024-11-19 13:02 UTC, merged